### ISSUE TITLE
BUG: Can't connect between two diffent platform

### ISSUE THREAD

**Issue by ghost** [jeromegn/quinn-plaintext#2]
When use this crate, client and server cant get connection between two diffent platform, such as win10-debian, freebsd-debian, but debian-debian will work, I have test mutipul combination none of these will work. 
plz fix it, thanks

**Comment by jeromegn** [comment]
Do you see any error logs? Can you use `tracing` and enable trace logging like this: `RUST_LOG=quinn=trace` when running it across platforms?

I first thought this could be an endianness issue, but if those are all x86_64 then that can't be it. The crate also uses a specific endianness anyway so it shouldn't matter.

**Comment by ghost** [comment]
thanks for reply, all the platforms are x86_64, i'll try to trace something out. or maybe it's quinn got wrong? have different behavior on different platform.

**Comment by jeromegn** [comment]
> maybe it's quinn got wrong? have different behavior on different platform.

If you remove quinn-plaintext out of the equation and still have issues, then yes that sounds like something else.

**Comment by ghost** [comment]
It's quinn's bug, any unusual certs will cause this problems, sorry for wasting your time

**Comment by jeromegn** [comment]
No problem! Thanks for investigating your issue deeper!
